<?php
if (function_exists('acf_add_local_field_group')) :

  acf_add_local_field_group(array(
    'key' => 'group_63eb316b4e6b5',
    'title' => 'Organization Page Settings',
    'fields' => array(
      array(
        'key' => 'field_63eb316c4e4ea',
        'label' => 'Excerpt',
        'name' => 'excerpt',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => 'This excerpt will be show on organization page.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'rows' => 4,
        'placeholder' => '',
        'new_lines' => '',
      ),
      array(
        'key' => 'field_63eb4e997c24e',
        'label' => 'Subtitle',
        'name' => 'subtitle',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This subtitle will be show on organization page.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63eb4ec17c24f',
        'label' => 'Address',
        'name' => 'address',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This address will be show on organization page.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63eb4ee57c250',
        'label' => 'Big Image',
        'name' => 'big_image',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => 'This image will be show on organization page.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'thumbnail',
      ),
      array(
        'key' => 'field_63eb501a1e65f',
        'label' => 'Project',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_63eb50311e660',
        'label' => 'Project Subtitle',
        'name' => 'project_subtitle',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This subtitle will be show on organization project section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63eb50951e662',
        'label' => 'Project Title',
        'name' => 'project_title',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => 'This title will be show on organization project section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'rows' => 4,
        'placeholder' => '',
        'new_lines' => '',
      ),
      array(
        'key' => 'field_63eb50d4035af',
        'label' => 'Project Image 1',
        'name' => 'project_image_1',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => 'This image will be show on organization project section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'thumbnail',
      ),
      array(
        'key' => 'field_63eb50ec035b0',
        'label' => 'Project Image 2',
        'name' => 'project_image_2',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => 'This image will be show on organization project section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'thumbnail',
      ),
      array(
        'key' => 'field_63eb505c1e661',
        'label' => 'Project Content',
        'name' => 'project_content',
        'aria-label' => '',
        'type' => 'wysiwyg',
        'instructions' => 'This content will be show on organization project section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_63eb5105b7bc1',
        'label' => 'Organization',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_63eb511db7bc2',
        'label' => 'Organization Subtitle',
        'name' => 'organisation_subtitle',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This subtitle will be show on organization organisation section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63eb514eb7bc3',
        'label' => 'Organiszation Feature',
        'name' => 'organisation_feature',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Add Feature',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_63eb515eb7bc4',
            'label' => 'Title',
            'name' => 'title',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_63eb514eb7bc3',
          ),
          array(
            'key' => 'field_63eb5179b7bc5',
            'label' => 'Feature List',
            'name' => 'feature_list',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'layout' => 'block',
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => 'Add List',
            'rows_per_page' => 20,
            'sub_fields' => array(
              array(
                'key' => 'field_63eb5188b7bc6',
                'label' => 'List Text',
                'name' => 'list_text',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'parent_repeater' => 'field_63eb5179b7bc5',
              ),
            ),
            'parent_repeater' => 'field_63eb514eb7bc3',
          ),
        ),
      ),
      array(
        'key' => 'field_63eb51cf491e1',
        'label' => 'Questions',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_63eb51da491e2',
        'label' => 'Questions Subtitle',
        'name' => 'questions_subtitle',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This subtitle will be show on organization questions section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63eb5205491e3',
        'label' => 'FAQs',
        'name' => 'faqs',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Add FAQ',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_63eb5211491e4',
            'label' => 'Question',
            'name' => 'question',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_63eb5205491e3',
          ),
          array(
            'key' => 'field_63eb521a491e5',
            'label' => 'Answer',
            'name' => 'answer',
            'aria-label' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'rows' => 3,
            'placeholder' => '',
            'new_lines' => '',
            'parent_repeater' => 'field_63eb5205491e3',
          ),
        ),
      ),
      array(
        'key' => 'field_63eb5272db0ff',
        'label' => 'Brief',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_63eb5286db100',
        'label' => 'Brief Title',
        'name' => 'brief_title',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => 'This title will be show on organization brif section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'rows' => 4,
        'placeholder' => '',
        'new_lines' => '',
      ),
      array(
        'key' => 'field_63eb52b2db101',
        'label' => 'Button Text',
        'name' => 'button_text',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63eb52d9db102',
        'label' => 'Button Link',
        'name' => 'button_link',
        'aria-label' => '',
        'type' => 'url',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'organizations',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
  ));

  acf_add_local_field_group(array(
    'key' => 'group_63ea10d87ab20',
    'title' => 'Project Page Settings',
    'fields' => array(
      array(
        'key' => 'field_63ea10d9bc990',
        'label' => 'Excerpt',
        'name' => 'excerpt',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => 'This excerpt will be show on project page.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'rows' => 4,
        'placeholder' => '',
        'new_lines' => '',
      ),
      array(
        'key' => 'field_63ea2d269c242',
        'label' => 'Address',
        'name' => 'address',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This address will be show on project page.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '25',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63faf8376e5f6',
        'label' => 'Delivery Date',
        'name' => 'delivery_date',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This date will be show on project page.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '25',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63eb0a50de427',
        'label' => 'Subtitle',
        'name' => 'subtitle',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This subtitle will be show on project page.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63eb0aa687302',
        'label' => 'Mission',
        'name' => 'mission',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This mission text will be show on project page.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63eb0d06b60e6',
        'label' => 'Big Image',
        'name' => 'big_image',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => 'This image will be show on project single page.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'thumbnail',
      ),
      array(
        'key' => 'field_63eb0eaba31f2',
        'label' => 'Agensis',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_63eb0f29d78a8',
        'label' => 'Agensis Content',
        'name' => 'agensis_content',
        'aria-label' => '',
        'type' => 'wysiwyg',
        'instructions' => 'This content will be show on project agensis section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_63eb0fdaf1cf8',
        'label' => 'Agensis Chat',
        'name' => 'agensis_chat',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Add Row',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_63eb0ffdf1cf9',
            'label' => 'Chat Image',
            'name' => 'chat_image',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'url',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'preview_size' => 'medium',
            'parent_repeater' => 'field_63eb0fdaf1cf8',
          ),
          array(
            'key' => 'field_63eb1020f1cfa',
            'label' => 'Chat Text',
            'name' => 'chat_text',
            'aria-label' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'rows' => 4,
            'placeholder' => '',
            'new_lines' => '',
            'parent_repeater' => 'field_63eb0fdaf1cf8',
          ),
        ),
      ),
      array(
        'key' => 'field_63eb1060fa8f0',
        'label' => 'Contexte',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_63eb10acfa8f1',
        'label' => 'Contexte Subtitle',
        'name' => 'contexte_subtitle',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This subtitle will be show on project contexte section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => 'Contexte',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63eb10dcfa8f2',
        'label' => 'Contexte Title',
        'name' => 'contexte_title',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This title will be show on project contexte section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63eb114d45287',
        'label' => 'Contexte Image 1',
        'name' => 'contexte_image_1',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => 'This image will be show on project contexte section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'thumbnail',
      ),
      array(
        'key' => 'field_63eb118945288',
        'label' => 'Contexte Image 2',
        'name' => 'contexte_image_2',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => 'This image will be show on project contexte section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'thumbnail',
      ),
      array(
        'key' => 'field_63eb111289dac',
        'label' => 'Contexte Content',
        'name' => 'contexte_content',
        'aria-label' => '',
        'type' => 'wysiwyg',
        'instructions' => 'This content will be show on project contexte section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_63eb11ddeeb10',
        'label' => 'Programming',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_63eb11e4eeb11',
        'label' => 'Programming Subtitle',
        'name' => 'programming_subtitle',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This subtitle will be show on project programming section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => 'La programmation',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63eb11eaeeb12',
        'label' => 'Programming Title',
        'name' => 'programming_title',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This title will be show on project programming section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63eb12bb56428',
        'label' => 'Programming Image',
        'name' => 'programming_image',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => 'This image will be show on project programming section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'thumbnail',
      ),
      array(
        'key' => 'field_63eb1244d0583',
        'label' => 'Programming Content',
        'name' => 'programming_content',
        'aria-label' => '',
        'type' => 'wysiwyg',
        'instructions' => 'This content will be show on project programming section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_63eb130ca304b',
        'label' => 'Programming Topic',
        'name' => 'programming_topic',
        'aria-label' => '',
        'type' => 'group',
        'instructions' => 'This topic will be show on project programming section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_63eb133fa304c',
            'label' => 'Topic Title',
            'name' => 'topic_title',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
          ),
          array(
            'key' => 'field_63eb139add43b',
            'label' => 'Topic List',
            'name' => 'topic_list',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'layout' => 'block',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => 'Add Topic',
            'rows_per_page' => 20,
            'sub_fields' => array(
              array(
                'key' => 'field_63eb13aedd43c',
                'label' => 'Topic Text',
                'name' => 'topic_text',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'rows' => 3,
                'placeholder' => '',
                'new_lines' => '',
                'parent_repeater' => 'field_63eb139add43b',
              ),
            ),
          ),
        ),
      ),
      array(
        'key' => 'field_63eb1418682a4',
        'label' => 'Architecture',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_63eb142c682a5',
        'label' => 'Architecture Subtitle',
        'name' => 'architecture_subtitle',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This subtitle will be show on project architecture section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => 'Concours d’architecture',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63eb1435682a6',
        'label' => 'Architecture Title',
        'name' => 'architecture_title',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This title will be show on project architecture section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63eb1447682a8',
        'label' => 'Architecture Image 1',
        'name' => 'architecture_image_1',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => 'This image will be show on project architecture section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'thumbnail',
      ),
      array(
        'key' => 'field_63eb143c682a7',
        'label' => 'Architecture Image 2',
        'name' => 'architecture_image_2',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => 'This image will be show on project architecture section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'thumbnail',
      ),
      array(
        'key' => 'field_63eb1456682a9',
        'label' => 'Architecture Content',
        'name' => 'architecture_content',
        'aria-label' => '',
        'type' => 'wysiwyg',
        'instructions' => 'This content will be show on project architecture section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_63eb151a33b45',
        'label' => 'Study',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_63eb152d33b47',
        'label' => 'Study Subtitle',
        'name' => 'study_subtitle',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This subtitle will be show on project study section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63eb153233b48',
        'label' => 'Study Title',
        'name' => 'study_title',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This title will be show on project study section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63eb154133b4a',
        'label' => 'Study Image',
        'name' => 'study_image',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => 'This image will be show on project study section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'thumbnail',
      ),
      array(
        'key' => 'field_63eb153733b49',
        'label' => 'Study Content',
        'name' => 'study_content',
        'aria-label' => '',
        'type' => 'wysiwyg',
        'instructions' => 'This content will be show on project study section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_63eb15c233b4b',
        'label' => 'Site',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_63eb15d233b4c',
        'label' => 'Site Subtitle',
        'name' => 'site_subtitle',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This subtitle will be show on project site section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63eb15d633b4d',
        'label' => 'Site Title',
        'name' => 'site_title',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This title will be show on project site section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63eb15db33b4e',
        'label' => 'Site Content',
        'name' => 'site_content',
        'aria-label' => '',
        'type' => 'wysiwyg',
        'instructions' => 'This content will be show on project site section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_63eb166233b4f',
        'label' => 'Winning',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_63eb167333b50',
        'label' => 'Winning Subtitle',
        'name' => 'winning_subtitle',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This subtitle will be show on project winning section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63eb167933b51',
        'label' => 'Winning Title',
        'name' => 'winning_title',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This title will be show on project winning section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63eb168533b53',
        'label' => 'Winning Big Image',
        'name' => 'winning_big_image',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => 'This image will be show on project winning section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'thumbnail',
      ),
      array(
        'key' => 'field_63eb167d33b52',
        'label' => 'Winning Content',
        'name' => 'winning_content',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => 'This content will be show on project winning section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'rows' => 4,
        'placeholder' => '',
        'new_lines' => '',
      ),
      array(
        'key' => 'field_63eb174e9e173',
        'label' => 'Winning Gallery',
        'name' => 'winning_gallery',
        'aria-label' => '',
        'type' => 'gallery',
        'instructions' => 'This images will be show on project winning section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'library' => 'all',
        'min' => '',
        'max' => 6,
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'insert' => 'append',
        'preview_size' => 'thumbnail',
      ),
      array(
        'key' => 'field_63eb179f9e174',
        'label' => 'Winning Finalist',
        'name' => 'winning_finalist',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => 'This finalist items will be show on winning section.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Add Finalist',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_63eb17ee9e175',
            'label' => 'Title',
            'name' => 'title',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_63eb179f9e174',
          ),
          array(
            'key' => 'field_63eb180b9e176',
            'label' => 'Images',
            'name' => 'images',
            'aria-label' => '',
            'type' => 'gallery',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'url',
            'library' => 'all',
            'min' => '',
            'max' => '',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'insert' => 'append',
            'preview_size' => 'thumbnail',
            'parent_repeater' => 'field_63eb179f9e174',
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'projects',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
  ));

  acf_add_local_field_group(array(
    'key' => 'group_63e9d3fd000c8',
    'title' => 'Service Page Setting',
    'fields' => array(
      array(
        'key' => 'field_63e9d48fd132d',
        'label' => 'Excerpt',
        'name' => 'excerpt',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => 'This excerpt will be show on service page.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'rows' => 4,
        'placeholder' => '',
        'new_lines' => '',
      ),
      array(
        'key' => 'field_63e9d3fdaf050',
        'label' => 'Subtitle',
        'name' => 'subtitle',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'This subtitle will be show on service page.',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_63e9d4d8d132e',
        'label' => 'Big Image',
        'name' => 'big_image',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => 'This image will be show on service page.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'thumbnail',
      ),
      array(
        'key' => 'field_63e9d53f368a5',
        'label' => 'Service Details',
        'name' => 'service_details',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => 'This details will be show on service page.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'rows' => 4,
        'placeholder' => '',
        'new_lines' => '',
      ),
      array(
        'key' => 'field_63e9d5b98f362',
        'label' => 'Stage Organization',
        'name' => 'stage_organization',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => 'This organization will be show on service page.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Add Organaization',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_63e9d60a8f363',
            'label' => 'Title',
            'name' => 'title',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_63e9d5b98f362',
          ),
          array(
            'key' => 'field_63e9d6268f364',
            'label' => 'Description',
            'name' => 'description',
            'aria-label' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'rows' => 3,
            'placeholder' => '',
            'new_lines' => '',
            'parent_repeater' => 'field_63e9d5b98f362',
          ),
          array(
            'key' => 'field_63e9d6338f365',
            'label' => 'Image',
            'name' => 'image',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'url',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'preview_size' => 'thumbnail',
            'parent_repeater' => 'field_63e9d5b98f362',
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'services',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
  ));

endif;
